HMS/urls.py
from django.contrib import admin
from django.urls import path, include
from room.views import RoomListView, RoomDetailView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', RoomListView.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('booking/', include('booking.urls')),
    path('guest/', include('guest.urls')),
    path('rooms/', include('room.urls')),
    path('room/<int:pk>', RoomDetailView.as_view(), name='room_detail'),
    path('reviews/', include('reviews.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.conf.urls.static import static
app_name = 'guest'

urlpatterns = [
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/models.py
from django.db import models
from django.urls import reverse


class Room(models.Model):
    ROOM_TYPES = (
        ('single', 'Single'),
        ('double', 'Double'),
        ('king', 'King')
    )

    room_number = models.CharField(max_length=10)
    room_type = models.CharField(max_length=10, choices=ROOM_TYPES)
    price = models.IntegerField()
    room_image = models.ImageField(upload_to='room_images/', height_field=None, width_field=None, max_length=None,
                                   default='0.jpeg')

    def __str__(self):
        return self.room_number

    # def get_absolute_url(self):
    #     return reverse('Room', kwargs={'room_id': self.pk})

room/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from .models import Room


class RoomListView(TemplateView):
    model = Room
    template_name = 'base/homepage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        room_types = Room.ROOM_TYPES
        rooms = [Room.objects.filter(room_type=room_type[0]).first() for room_type in room_types]
        context['rooms'] = rooms
        for i in rooms:
            print(i.room_image)
        return context


class RoomDetailView(DetailView):
    model = Room
    template_name = 'rooms/room_detail.html'
    context_object_name = 'room'

templates/rooms/room_delete.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>Delete Room</h1>
  <p>Are you sure you want to delete {{ object.room_number }}?</p>
  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
    <a href="{% url 'room:room_list' %}">Cancel</a>
  </form>
{% endblock %}

templates/rooms/room_detail.html
{% extends 'base/base.html' %}
 {%load static %}
{% block content %}
<div class="content">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <h1>Room number {{ room.room_number }}</h1>
    <p>Number of beds: {{ room.room_type }}</p>
    <p>Price per night: {{ room.price }}</p>
  </div>

{% endblock %}

templates/rooms/room_form.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>{% if form.instance.pk %}Edit{% else %}Add{% endif %} Room</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
  </form>
{% endblock %}

templates/rooms/room_list.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>Rooms</h1>
  <ul>

  {% for room in rooms %}
    <tr>
      <p>aboba</p>
    <td>{{room.room_number}}</td>
      <td>
        <a href="{% url 'room:room_detail' room.id %}">detail</a>
        <a href="{% url 'room:room_delete' room.id %}">Delete</a>
        <a href="{% url 'room:room_update' room.id %}">Edit</a>
      </td>
      <td>{{ room.room_type }}</td>
    </tr>
  {% empty %}
    <li><a href="{% url 'room:room_create' %}">Add Room</a></li>
    <li>No rooms found.</li>
  {% endfor %}
  </ul>
{% endblock %}