HMS/urls.py
from django.contrib import admin
from django.urls import path, include
from room.views import RoomListView, RoomDetailView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', RoomListView.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('booking/', include('booking.urls')),
    path('guest/', include('guest.urls')),
    path('rooms/', include('room.urls')),
    path('room/<int:pk>', RoomDetailView.as_view(), name='room_detail'),
    path('reviews/', include('reviews.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from .views import ReviewCreateView, ReviewUpdateView, ReviewListView, ReviewDeleteView

app_name = 'reviews'

urlpatterns = [
    path('', ReviewListView.as_view(), name='review_list'),
    path('create/', ReviewCreateView.as_view(), name='review_create'),
    path('edit/<int:pk>/', ReviewUpdateView.as_view(), name='review_edit'),
    path('delete/', ReviewDeleteView.as_view(), name='review_delete'),
]

reviews/models.py
from django.db import models
from guest.models import Guest


class Review(models.Model):
    user = models.ForeignKey(Guest, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

reviews/forms.py
from django import forms
from .models import Review
from .services import kmp_search


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('title', 'content')

    def clean(self):
        cleaned_data = super().clean()
        content = cleaned_data.get('content')
        censored_words = ['Плохо', 'Ужасно', 'Отвратительно', 'Не нравится', 'Абоба']
        if content and kmp_search(content, censored_words):
            raise ValidationError('Отзыв содержит запрещенные слова.')

        return cleaned_data

reviews/views.py
import datetime

from django.contrib import messages
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import Review
from .forms import ReviewForm
from .services import kmp_search


class ReviewListView(ListView):
    model = Review
    template_name = 'reviews/review_list.html'
    context_object_name = 'reviews'
    paginate_by = 10

    def get_queryset(self):
        return super().get_queryset().order_by('-created_at')


class ReviewCreateView(CreateView):
    model = Review
    form_class = ReviewForm
    template_name = 'reviews/review_form.html'
    success_url = reverse_lazy('reviews:review_list')

    def form_valid(self, form):
        review = form.save(commit=False)
        review.user = self.request.user  # Привязываем отзыв к текущему пользователю
        text = form.cleaned_data['content']
        censored_words = ['Плохо', 'Ужасно', 'Отвратительно', 'Не нравится', 'Абоба']

        for word in censored_words:
            if kmp_search(word.lower(), text.lower()):
                messages.error(self.request, f'Текст содержит недопустимые выражения ("{word}").')
                return super().form_invalid(form)

        review.save()
        return super().form_valid(form)


class ReviewUpdateView(UpdateView):
    model = Review
    form_class = ReviewForm
    template_name = 'reviews/review_form.html'
    success_url = reverse_lazy('reviews:review_list')

    def form_valid(self, form):
        review = form.instance
        text = form.cleaned_data['content']
        censored_words = ['Плохо', 'Ужасно', 'Отвратительно', 'Не нравится', 'Абоба']

        for word in censored_words:
            if kmp_search(word.lower(), text.lower()):
                messages.error(self.request, f'Текст содержит недопустимые выражения ("{word}").')
                return super().form_invalid(form)

        review.created_at = datetime.datetime.now()
        return super().form_valid(form)


class ReviewDeleteView(View):
    def post(self, request, *args, **kwargs):
        review_id = request.POST.get('review_id')
        try:
            review = Review.objects.get(id=review_id, user=request.user)
            review.delete()
            return JsonResponse({'success': True})
        except Review.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Review not found or you are not the author.'})

templates/reviews/review_form.html
{% extends 'base/base.html' %}

{% block content %}
  <div class="container">
    <h1>Create Review</h1>
    <form method="post" class="my-4">
      {% csrf_token %}
      {{ form.as_p }}
      {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
{% endblock %}

templates/reviews/review_list.html
{% extends 'base/base.html' %}

{% block content %}
  <div class="container">
    <h1>Отзывы</h1>
    {% if user.is_authenticated %}
      <a href="{% url 'reviews:review_create' %}" class="btn btn-primary mb-3">Добавить отзыв</a>
    {% endif %}
    {% for review in reviews %}
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">{{ review.title }}</h5>
          <p class="card-text">{{ review.content }}</p>
          <p class="card-text">Автор: {{ review.user }}</p>
          <p class="card-text">Дата публикации: {{ review.created_at }}</p>
          {% if user.is_authenticated and user == review.user %}
            <div class="float-end">
              <a href="{% url 'reviews:review_edit' review.id %}" class="btn btn-sm btn-secondary me-1">Редактировать</a>
              <button class="btn btn-sm btn-danger delete-review-btn" data-review-id="{{ review.id }}">Удалить</button>
            </div>
          {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>

  <script>
    $(document).ready(function() {
      $('.delete-review-btn').click(function() {
        var reviewId = $(this).data('review-id');
        $.ajax({
          url: "{% url 'reviews:review_delete' %}",
          type: "POST",
          data: {
            'review_id': reviewId,
            'csrfmiddlewaretoken': "{{ csrf_token }}"
          },
          success: function(response) {
            if (response.success) {
              // Успешное удаление отзыва
              location.reload()
            } else {
              // Ошибка удаления отзыва
              console.log(response.error);
            }
          },
          error: function(xhr, status, error) {
            // Обработка ошибки AJAX
            console.log(error);
          }
        });
      });
    });
  </script>
{% endblock %}